# Generated by Django 3.2.6 on 2021-09-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Car_License_Number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Picture_For_Car_License_Number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
